url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: Sites By Steph # the name of your site, e.g. ACME Corp.
tagline: Freelance web design and web development services from Philadelphia.
email: email
description: >-
  Our human centric approach to web design and web development are
author: me
plugins:
  - jekyll-autoprefixer
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji
collections:
  sections:
    sort_by: order
